import java.lang.Exception

fun main(){



    var calculo = CalculoMatematico();

    println(calculo.divisao(4,0))
    

}